### ISSUE TITLE
Les nouveaux nœuds ne sont pas détectés par Jeedom

### ISSUE THREAD

**Issue by dough29** [lunarok/jeedom_mySensors#3]
Bonjour,

je fais suite au sujet ouvert sur le forum Jeedom ici : https://www.jeedom.com/forum/viewtopic.php?f=35&t=20324

Je créé hier un nouveau nœud MySensors sur une installation toute neuve et à jour sur un Raspberry Pi.

Dans les logs tout semble fonctionner car je reçois bien les messages du nœud dans le log Jeedom/MySensors :

    Wed Nov 09 2016 00:00:47 GMT+0100 (CET) : http://192.168.0.3:80/plugins/mySensors/core/api/jeeSensors.php?apikey=APIKEY&gateway=master&messagetype=saveValue&sender=1&sensor=3&type=16&payload=1
    Wed Nov 09 2016 00:00:47 GMT+0100 (CET) : 1;3;1;0;16;1
    Wed Nov 09 2016 00:01:16 GMT+0100 (CET) : http://192.168.0.3:80/plugins/mySensors/core/api/jeeSensors.php?apikey=APIKEY&gateway=master&messagetype=saveValue&sender=1&sensor=4&type=16&payload=0
    Wed Nov 09 2016 00:01:16 GMT+0100 (CET) : 1;4;1;0;16;0

Malgré que le plugin soit en mode "inclusion" rien ne se passe côté Jeedom.

Toutes les traces sont en niveau debug et rien ne sort dans les divers logs Jeedom.

**Comment by lunarok** [comment]
Je ne fais pas de support ici pour ca, pas plus que sur des fils du forum qui ne sont pas ceux du plugin.
Il faut demander sur le fil du plugin mais avec les logs complets, la le node dit bien qu'il a contacte jeedom donc il y a des logs mySensors équivalent a ces appels

**Comment by dough29** [comment]
Merci de ta réponse, c'est noté.
